/**
 * Discovery and codegen for src/.generated/mockup-components.ts.
 *
 * src/App.tsx imports that module, but it is gitignored and regenerated on
 * every run, so on a fresh clone it does not exist. That was fine while the
 * only thing that ever read it was Vite - mockupPreviewPlugin writes it in
 * buildStart and configureServer, before anything resolves the import.
 *
 * `tsc --noEmit` is not Vite. It resolves the import with no plugin in sight
 * and fails, which is exactly what `pnpm typecheck` did on a fresh clone:
 *
 *   src/App.tsx(3,46): error TS2307: Cannot find module './.generated/mockup-components'
 *
 * So the generation lives here, callable without Vite, and both paths use it:
 * the plugin for dev and build, and the `pretypecheck` script for tsc. One
 * implementation - a second copy of the discovery rules would be the drift
 * this file exists to prevent.
 *
 * ── Why .mjs and not .ts ────────────────────────────────────────────────────
 * The pretypecheck script has to run BEFORE tsc, so it cannot be TypeScript
 * without a TS runtime, and adding `tsx` here just to run one 40-line file
 * pulls a dependency into this package for no gain. Plain ESM runs under the
 * node that is already there. Types for the plugin's import live in the
 * sibling .d.mts.
 *
 * Run standalone: node generateMockupModule.mjs [root]
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import glob from "fast-glob";

export const MOCKUPS_DIR = "src/components/mockups";
export const GENERATED_MODULE = "src/.generated/mockup-components.ts";

/**
 * Every .tsx under the mockups dir, excluding anything whose file or directory
 * name starts with an underscore - the convention for "not a preview target".
 *
 * Sorted, so the generated file is stable and does not churn in a diff just
 * because the filesystem handed the entries back in a different order.
 */
export async function discoverComponents(root) {
  const files = await glob(`${MOCKUPS_DIR}/**/*.tsx`, {
    cwd: root,
    ignore: ["**/_*/**", "**/_*.tsx"],
  });

  return files.sort().map((f) => ({
    globKey: "./" + f.slice("src/".length),
    importPath: path.posix.relative("src/.generated", f),
  }));
}

export function generateSource(components) {
  const entries = components
    .map(
      (c) =>
        `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`,
    )
    .join(",\n");

  return [
    "// This file is auto-generated by generateMockupModule.mjs.",
    "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
    "export const modules: ModuleMap = {",
    entries,
    "};",
    "",
  ].join("\n");
}

/**
 * Writes the module only if its content would change. Returns the source either
 * way, so a caller can hold it as its "current" state, plus whether it wrote.
 */
export async function writeGeneratedModule(root) {
  const components = await discoverComponents(root);
  const source = generateSource(components);
  const target = path.join(root, GENERATED_MODULE);

  const existing = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (existing === source) return { source, changed: false };

  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, source);
  return { source, changed: true };
}

// Standalone entry, used by the pretypecheck and prebuild scripts.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const root = process.argv[2] ? path.resolve(process.argv[2]) : process.cwd();
  const { changed } = await writeGeneratedModule(root);
  console.log(`[mockup-components] ${changed ? "wrote" : "up to date"} ${GENERATED_MODULE}`);
}
