/**
 * Seed all staff (12 types, ~115 members) with portraits uploaded to GCS.
 * Run: pnpm --filter @workspace/scripts run seed-staff
 */

import { Storage } from "@google-cloud/storage";
import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { db } from "@workspace/db";
import { staffTable } from "@workspace/db/schema";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = resolve(__dirname, "../../");

const SIDECAR = "http://127.0.0.1:1106";
const PRIVATE_OBJECT_DIR = process.env.PRIVATE_OBJECT_DIR!;

if (!PRIVATE_OBJECT_DIR) {
  console.error("Missing PRIVATE_OBJECT_DIR");
  process.exit(1);
}

const gcs = new Storage({
  credentials: {
    audience: "replit",
    subject_token_type: "access_token",
    token_url: `${SIDECAR}/token`,
    type: "external_account",
    credential_source: {
      url: `${SIDECAR}/credential`,
      format: { type: "json", subject_token_field_name: "access_token" },
    },
    universe_domain: "googleapis.com",
  } as object,
  projectId: "",
});

async function uploadImage(localPath: string, entityId: string): Promise<string> {
  const privateDir = PRIVATE_OBJECT_DIR.endsWith("/")
    ? PRIVATE_OBJECT_DIR
    : `${PRIVATE_OBJECT_DIR}/`;

  const parts = privateDir.startsWith("/") ? privateDir.slice(1) : privateDir;
  const slashIdx = parts.indexOf("/");
  const bucketName = slashIdx === -1 ? parts.replace(/\/$/, "") : parts.slice(0, slashIdx);
  const prefix = slashIdx === -1 ? "" : parts.slice(slashIdx + 1);

  const objectName = `${prefix}${entityId}`;
  const bucket = gcs.bucket(bucketName);
  const file = bucket.file(objectName);

  const content = readFileSync(localPath);
  await file.save(content, {
    contentType: "image/webp",
    metadata: { cacheControl: "public, max-age=31536000" },
  });

  console.log(`  uploaded → gs://${bucketName}/${objectName}`);
  return `/objects/${entityId}`;
}

interface StaffDef {
  name: string;
  nationality: string;
  age: number;
  role: string;
  specialty: string;
  salary: number;
  skillLevel: number;
  overallRating: number;
  coachSpeciality: string;
  personality: string;
  attributes: Record<string, number>;
  specialTrait: string;
  scoutingRating: number;
  imageFile: string;
}

// ─── HEAD COACHES ────────────────────────────────────────────────────────────
const HEAD_COACHES: StaffDef[] = [
  {
    name: "Valentina Greco",
    nationality: "Italy",
    age: 49,
    role: "Head Coach",
    specialty: "Tactical Excellence",
    salary: 280000,
    skillLevel: 96,
    overallRating: 95,
    coachSpeciality: "Tactics",
    personality: "Tactician",
    attributes: { tactics: 97, motivation: 88, offense: 92, defense: 90, playerDevelopment: 85 },
    specialTrait: "Grand Slam Winner",
    scoutingRating: 50,
    imageFile: "staff_head_coach_01_1783380284480.webp",
  },
  {
    name: "Mariana Souza",
    nationality: "Brazil",
    age: 52,
    role: "Head Coach",
    specialty: "Attack & Serve Pressure",
    salary: 265000,
    skillLevel: 93,
    overallRating: 92,
    coachSpeciality: "Offense",
    personality: "Motivator",
    attributes: { tactics: 90, motivation: 95, offense: 96, defense: 84, playerDevelopment: 88 },
    specialTrait: "Olympic Gold Medallist",
    scoutingRating: 50,
    imageFile: "staff_head_coach_02_1783380288140.webp",
  },
  {
    name: "Sun Li",
    nationality: "China",
    age: 44,
    role: "Head Coach",
    specialty: "Defence & Blocking",
    salary: 240000,
    skillLevel: 90,
    overallRating: 90,
    coachSpeciality: "Defense",
    personality: "Disciplinarian",
    attributes: { tactics: 88, motivation: 84, offense: 79, defense: 96, playerDevelopment: 87 },
    specialTrait: "Wall of Steel",
    scoutingRating: 50,
    imageFile: "staff_head_coach_03_1783380290204.webp",
  },
  {
    name: "Anika Hoffmann",
    nationality: "Germany",
    age: 46,
    role: "Head Coach",
    specialty: "Player Development",
    salary: 215000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Development",
    personality: "Developer",
    attributes: { tactics: 84, motivation: 86, offense: 83, defense: 82, playerDevelopment: 95 },
    specialTrait: "Youth Specialist",
    scoutingRating: 50,
    imageFile: "staff_head_coach_04_1783380292661.webp",
  },
  {
    name: "Fatima Al-Rashid",
    nationality: "Qatar",
    age: 41,
    role: "Head Coach",
    specialty: "Serve & Receive System",
    salary: 190000,
    skillLevel: 84,
    overallRating: 84,
    coachSpeciality: "Serve & Receive",
    personality: "Tactician",
    attributes: { tactics: 86, motivation: 82, offense: 85, defense: 84, playerDevelopment: 81 },
    specialTrait: "Serve Maestro",
    scoutingRating: 50,
    imageFile: "staff_head_coach_05_1783380294602.webp",
  },
  {
    name: "Elena Popova",
    nationality: "Russia",
    age: 55,
    role: "Head Coach",
    specialty: "All-Round Strategy",
    salary: 175000,
    skillLevel: 79,
    overallRating: 80,
    coachSpeciality: "General",
    personality: "Motivator",
    attributes: { tactics: 82, motivation: 85, offense: 78, defense: 80, playerDevelopment: 79 },
    specialTrait: "Veteran Leader",
    scoutingRating: 50,
    imageFile: "staff_head_coach_06_1783380385110.webp",
  },
  {
    name: "Priya Nair",
    nationality: "India",
    age: 38,
    role: "Head Coach",
    specialty: "Mental Toughness & Motivation",
    salary: 155000,
    skillLevel: 76,
    overallRating: 77,
    coachSpeciality: "Motivation",
    personality: "Motivator",
    attributes: { tactics: 74, motivation: 94, offense: 75, defense: 76, playerDevelopment: 83 },
    specialTrait: "Mindset Coach",
    scoutingRating: 50,
    imageFile: "staff_head_coach_07_1783380404732.webp",
  },
  {
    name: "Sofia Andersen",
    nationality: "Denmark",
    age: 43,
    role: "Head Coach",
    specialty: "Tactical Flexibility",
    salary: 145000,
    skillLevel: 73,
    overallRating: 74,
    coachSpeciality: "Tactics",
    personality: "Tactician",
    attributes: { tactics: 78, motivation: 75, offense: 73, defense: 74, playerDevelopment: 72 },
    specialTrait: "Set Play Expert",
    scoutingRating: 50,
    imageFile: "staff_head_coach_08_1783380301612.webp",
  },
  {
    name: "Amara Diallo",
    nationality: "Senegal",
    age: 39,
    role: "Head Coach",
    specialty: "Speed & Athleticism",
    salary: 130000,
    skillLevel: 69,
    overallRating: 70,
    coachSpeciality: "Athletics",
    personality: "Developer",
    attributes: { tactics: 70, motivation: 80, offense: 72, defense: 68, playerDevelopment: 76 },
    specialTrait: "Athletic Developer",
    scoutingRating: 50,
    imageFile: "staff_head_coach_09_1783380303547.webp",
  },
  {
    name: "Zara Williams",
    nationality: "Australia",
    age: 37,
    role: "Head Coach",
    specialty: "Fast-Break Offence",
    salary: 118000,
    skillLevel: 64,
    overallRating: 65,
    coachSpeciality: "Offense",
    personality: "Disciplinarian",
    attributes: { tactics: 66, motivation: 70, offense: 74, defense: 63, playerDevelopment: 67 },
    specialTrait: "Attack Focused",
    scoutingRating: 50,
    imageFile: "staff_head_coach_10_1783380306109.webp",
  },
];

// ─── ASSISTANT COACHES ───────────────────────────────────────────────────────
const ASSISTANT_COACHES: StaffDef[] = [
  {
    name: "Lukas Schmidt",
    nationality: "Germany",
    age: 37,
    role: "Assistant Coach",
    specialty: "Tactics & Game Strategy",
    salary: 118000,
    skillLevel: 90,
    overallRating: 87,
    coachSpeciality: "Tactics",
    personality: "Tactician",
    attributes: { matchPreparation: 95, tacticalKnowledge: 96, offense: 89, defense: 88, playerDevelopment: 80 },
    specialTrait: "Game Analyst",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_01_1783380044229.webp",
  },
  {
    name: "Mei-Ling Tan",
    nationality: "Singapore",
    age: 31,
    role: "Assistant Coach",
    specialty: "Technical Skills & Serve",
    salary: 96000,
    skillLevel: 90,
    overallRating: 87,
    coachSpeciality: "Serve & Receive",
    personality: "Developer",
    attributes: { matchPreparation: 82, tacticalKnowledge: 86, offense: 92, defense: 80, playerDevelopment: 90 },
    specialTrait: "Serve Technician",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_02_1783380046835.webp",
  },
  {
    name: "Kwame Adu",
    nationality: "Ghana",
    age: 40,
    role: "Assistant Coach",
    specialty: "Strength & Conditioning",
    salary: 121000,
    skillLevel: 90,
    overallRating: 87,
    coachSpeciality: "Conditioning",
    personality: "Disciplinarian",
    attributes: { matchPreparation: 85, tacticalKnowledge: 82, offense: 84, defense: 86, playerDevelopment: 88 },
    specialTrait: "Power Builder",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_03_1783380049069.webp",
  },
  {
    name: "Isabella Ricci",
    nationality: "Italy",
    age: 34,
    role: "Assistant Coach",
    specialty: "Defense & Court Positioning",
    salary: 99000,
    skillLevel: 90,
    overallRating: 87,
    coachSpeciality: "Defense",
    personality: "Tactician",
    attributes: { matchPreparation: 88, tacticalKnowledge: 90, offense: 77, defense: 96, playerDevelopment: 85 },
    specialTrait: "Court Reader",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_04_1783380051200.webp",
  },
  {
    name: "Jessica De Groot",
    nationality: "Australia",
    age: 38,
    role: "Assistant Coach",
    specialty: "Setting & Game Analysis",
    salary: 112000,
    skillLevel: 90,
    overallRating: 87,
    coachSpeciality: "Setting",
    personality: "Tactician",
    attributes: { matchPreparation: 93, tacticalKnowledge: 92, offense: 87, defense: 89, playerDevelopment: 90 },
    specialTrait: "Video Analyst",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_05_1783380053456.webp",
  },
  {
    name: "Anouk Van Dijk",
    nationality: "Netherlands",
    age: 47,
    role: "Assistant Coach",
    specialty: "All-Rounder Strategy",
    salary: 71000,
    skillLevel: 58,
    overallRating: 58,
    coachSpeciality: "General",
    personality: "Motivator",
    attributes: { matchPreparation: 72, tacticalKnowledge: 74, offense: 71, defense: 72, playerDevelopment: 73 },
    specialTrait: "Experienced Hand",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_06_1783380055579.webp",
  },
  {
    name: "Emma Watson",
    nationality: "Australia",
    age: 42,
    role: "Assistant Coach",
    specialty: "Defensive Strategy",
    salary: 81000,
    skillLevel: 66,
    overallRating: 66,
    coachSpeciality: "Defense",
    personality: "Disciplinarian",
    attributes: { matchPreparation: 78, tacticalKnowledge: 82, offense: 66, defense: 89, playerDevelopment: 77 },
    specialTrait: "Defensive Mastermind",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_07_1783380058059.webp",
  },
  {
    name: "Sofia Martinez",
    nationality: "Spain",
    age: 34,
    role: "Assistant Coach",
    specialty: "Defensive Strategy",
    salary: 69000,
    skillLevel: 58,
    overallRating: 58,
    coachSpeciality: "Defense",
    personality: "Developer",
    attributes: { matchPreparation: 73, tacticalKnowledge: 75, offense: 65, defense: 82, playerDevelopment: 76 },
    specialTrait: "Blocker Specialist",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_08_1783380060168.webp",
  },
  {
    name: "Marcos Silva",
    nationality: "Brazil",
    age: 46,
    role: "Assistant Coach",
    specialty: "Player Development",
    salary: 76000,
    skillLevel: 58,
    overallRating: 58,
    coachSpeciality: "Development",
    personality: "Developer",
    attributes: { matchPreparation: 70, tacticalKnowledge: 73, offense: 75, defense: 73, playerDevelopment: 94 },
    specialTrait: "Talent Nurturer",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_09_1783380062261.webp",
  },
  {
    name: "Luca Bardi",
    nationality: "Australia",
    age: 38,
    role: "Assistant Coach",
    specialty: "Offensive Strategy",
    salary: 104000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Offense",
    personality: "Motivator",
    attributes: { matchPreparation: 90, tacticalKnowledge: 89, offense: 95, defense: 74, playerDevelopment: 84 },
    specialTrait: "Attack Catalyst",
    scoutingRating: 50,
    imageFile: "staff_assistant_coach_10_1783380064542.webp",
  },
];

// ─── FITNESS TRAINERS (no images 07/08) ──────────────────────────────────────
const FITNESS_TRAINERS: StaffDef[] = [
  {
    name: "Sophie Martin",
    nationality: "France",
    age: 28,
    role: "Fitness Trainer",
    specialty: "Strength Training & Sports Nutrition",
    salary: 84000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Fitness",
    personality: "Developer",
    attributes: { strengthTraining: 91, conditioning: 90, speedDevelopment: 84, agility: 86, endurance: 88, injuryPrevention: 87 },
    specialTrait: "Injury Shield",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_01_1783380170419.webp",
  },
  {
    name: "Eleni Papadopoulos",
    nationality: "Greece",
    age: 32,
    role: "Fitness Trainer",
    specialty: "Flexibility & Recovery",
    salary: 89000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Recovery",
    personality: "Developer",
    attributes: { strengthTraining: 88, conditioning: 85, speedDevelopment: 82, agility: 93, endurance: 84, injuryPrevention: 90 },
    specialTrait: "Recovery Specialist",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_02_1783380173056.webp",
  },
  {
    name: "Isabella Rodriguez",
    nationality: "Brazil",
    age: 30,
    role: "Fitness Trainer",
    specialty: "Speed & Mobility",
    salary: 86000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Speed",
    personality: "Motivator",
    attributes: { strengthTraining: 90, conditioning: 87, speedDevelopment: 91, agility: 92, endurance: 83, injuryPrevention: 89 },
    specialTrait: "Speed Developer",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_03_1783380174918.webp",
  },
  {
    name: "Natalie Thompson",
    nationality: "Canada",
    age: 34,
    role: "Fitness Trainer",
    specialty: "Strength & Rehabilitation",
    salary: 93000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Rehabilitation",
    personality: "Developer",
    attributes: { strengthTraining: 89, conditioning: 92, speedDevelopment: 84, agility: 83, endurance: 91, injuryPrevention: 90 },
    specialTrait: "Rehab Expert",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_04_1783380176825.webp",
  },
  {
    name: "Lucía Martínez",
    nationality: "Spain",
    age: 28,
    role: "Fitness Trainer",
    specialty: "Mobility & Performance Testing",
    salary: 85000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Performance",
    personality: "Developer",
    attributes: { strengthTraining: 87, conditioning: 84, speedDevelopment: 88, agility: 94, endurance: 82, injuryPrevention: 85 },
    specialTrait: "Agility Master",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_05_1783380178970.webp",
  },
  {
    name: "Mateo Gonzalez",
    nationality: "Argentina",
    age: 33,
    role: "Fitness Trainer",
    specialty: "Athletic Performance",
    salary: 90000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Athletics",
    personality: "Disciplinarian",
    attributes: { strengthTraining: 94, conditioning: 92, speedDevelopment: 90, agility: 85, endurance: 91, injuryPrevention: 88 },
    specialTrait: "Peak Performer",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_06_1783380181524.webp",
  },
  {
    name: "Lauren Johnson",
    nationality: "United States",
    age: 27,
    role: "Fitness Trainer",
    specialty: "Nutrition & Injury Prevention",
    salary: 61000,
    skillLevel: 51,
    overallRating: 51,
    coachSpeciality: "Nutrition",
    personality: "Developer",
    attributes: { strengthTraining: 73, conditioning: 71, speedDevelopment: 74, agility: 76, endurance: 72, injuryPrevention: 78 },
    specialTrait: "Prevention First",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_09_1783380188194.webp",
  },
  {
    name: "Lucas Anderson",
    nationality: "Australia",
    age: 32,
    role: "Fitness Trainer",
    specialty: "Strength & Performance Enhancement",
    salary: 97000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Strength",
    personality: "Disciplinarian",
    attributes: { strengthTraining: 96, conditioning: 95, speedDevelopment: 92, agility: 88, endurance: 94, injuryPrevention: 93 },
    specialTrait: "Iron Foundation",
    scoutingRating: 50,
    imageFile: "staff_fitness_trainer_10_1783380190822.webp",
  },
];

// ─── MEDICAL DOCTORS ─────────────────────────────────────────────────────────
const MEDICAL_DOCTORS: StaffDef[] = [
  {
    name: "Dr. Amara Osei",
    nationality: "Ghana",
    age: 44,
    role: "Doctor",
    specialty: "Sports Medicine & Injury Management",
    salary: 165000,
    skillLevel: 92,
    overallRating: 92,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 94, treatment: 92, rehabilitation: 88, injuryPrevention: 90 },
    specialTrait: "Rapid Diagnosis",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_01_1782964044103.webp",
  },
  {
    name: "Dr. Yuki Tanaka",
    nationality: "Japan",
    age: 38,
    role: "Doctor",
    specialty: "Performance Medicine & Recovery",
    salary: 148000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 88, treatment: 87, rehabilitation: 90, injuryPrevention: 85 },
    specialTrait: "Recovery Booster",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_02_1782964044104.webp",
  },
  {
    name: "Dr. Carlos Mendez",
    nationality: "Mexico",
    age: 51,
    role: "Doctor",
    specialty: "Orthopaedic Sports Medicine",
    salary: 172000,
    skillLevel: 90,
    overallRating: 90,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 92, treatment: 90, rehabilitation: 87, injuryPrevention: 88 },
    specialTrait: "Joint Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_03_1782964044105.webp",
  },
  {
    name: "Dr. Ingrid Larsson",
    nationality: "Sweden",
    age: 46,
    role: "Doctor",
    specialty: "Athletic Injury & Rehabilitation",
    salary: 158000,
    skillLevel: 88,
    overallRating: 88,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 89, treatment: 88, rehabilitation: 92, injuryPrevention: 86 },
    specialTrait: "Rehab Master",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_04_1782964044105.webp",
  },
  {
    name: "Dr. Nadia Khalil",
    nationality: "Egypt",
    age: 42,
    role: "Doctor",
    specialty: "Muscle & Tendon Injuries",
    salary: 143000,
    skillLevel: 85,
    overallRating: 85,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 86, treatment: 85, rehabilitation: 84, injuryPrevention: 89 },
    specialTrait: "Soft Tissue Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_05_1782964044105.webp",
  },
  {
    name: "Dr. Wei Chen",
    nationality: "China",
    age: 48,
    role: "Doctor",
    specialty: "Acupuncture & Sports Recovery",
    salary: 138000,
    skillLevel: 83,
    overallRating: 83,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 84, treatment: 83, rehabilitation: 86, injuryPrevention: 85 },
    specialTrait: "Holistic Healer",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_06_1782964044105.webp",
  },
  {
    name: "Dr. Tanya Petrov",
    nationality: "Russia",
    age: 39,
    role: "Doctor",
    specialty: "Cardio-Respiratory Performance",
    salary: 128000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 81, treatment: 80, rehabilitation: 78, injuryPrevention: 83 },
    specialTrait: "Endurance Doctor",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_07_1782964044106.webp",
  },
  {
    name: "Dr. Emmanuel Balogun",
    nationality: "Nigeria",
    age: 55,
    role: "Doctor",
    specialty: "General Sports Medicine",
    salary: 115000,
    skillLevel: 76,
    overallRating: 76,
    coachSpeciality: "Medical",
    personality: "Motivator",
    attributes: { diagnosis: 77, treatment: 76, rehabilitation: 75, injuryPrevention: 78 },
    specialTrait: "Veteran Medic",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_08_1782964044106.webp",
  },
  {
    name: "Dr. Laura Rossi",
    nationality: "Italy",
    age: 35,
    role: "Doctor",
    specialty: "Concussion & Neurological Care",
    salary: 152000,
    skillLevel: 86,
    overallRating: 86,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 90, treatment: 86, rehabilitation: 84, injuryPrevention: 82 },
    specialTrait: "Head Injury Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_09_1782964044106.webp",
  },
  {
    name: "Dr. Ana Lima",
    nationality: "Brazil",
    age: 41,
    role: "Doctor",
    specialty: "Preventive Sports Medicine",
    salary: 107000,
    skillLevel: 73,
    overallRating: 73,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 74, treatment: 73, rehabilitation: 75, injuryPrevention: 86 },
    specialTrait: "Prevention Focused",
    scoutingRating: 50,
    imageFile: "staff_medical_doctor_10_1782964044107.webp",
  },
];

// ─── MEDICAL PHYSIOTHERAPISTS (01–09 only) ────────────────────────────────────
const MEDICAL_PHYSIOTHERAPISTS: StaffDef[] = [
  {
    name: "Sarah O'Brien",
    nationality: "Ireland",
    age: 36,
    role: "Physiotherapist",
    specialty: "Musculoskeletal Rehabilitation",
    salary: 142000,
    skillLevel: 91,
    overallRating: 91,
    coachSpeciality: "Physiotherapy",
    personality: "Developer",
    attributes: { manipulation: 93, rehabilitation: 94, recovery: 90, injuryAssessment: 92 },
    specialTrait: "Full Recovery",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_01_1783046698965.webp",
  },
  {
    name: "Hana Novak",
    nationality: "Czech Republic",
    age: 33,
    role: "Physiotherapist",
    specialty: "Athletic Movement & Mobility",
    salary: 126000,
    skillLevel: 86,
    overallRating: 86,
    coachSpeciality: "Physiotherapy",
    personality: "Developer",
    attributes: { manipulation: 87, rehabilitation: 88, recovery: 89, injuryAssessment: 85 },
    specialTrait: "Movement Analyst",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_02_1783046708460.webp",
  },
  {
    name: "Yemi Adeyemi",
    nationality: "Nigeria",
    age: 41,
    role: "Physiotherapist",
    specialty: "Sports Injury Rehabilitation",
    salary: 138000,
    skillLevel: 89,
    overallRating: 89,
    coachSpeciality: "Physiotherapy",
    personality: "Tactician",
    attributes: { manipulation: 90, rehabilitation: 92, recovery: 88, injuryAssessment: 91 },
    specialTrait: "Recovery Champion",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_03_1783046717623.webp",
  },
  {
    name: "Kirra Walsh",
    nationality: "Australia",
    age: 29,
    role: "Physiotherapist",
    specialty: "Ankle & Knee Rehab",
    salary: 118000,
    skillLevel: 83,
    overallRating: 83,
    coachSpeciality: "Physiotherapy",
    personality: "Developer",
    attributes: { manipulation: 84, rehabilitation: 86, recovery: 85, injuryAssessment: 82 },
    specialTrait: "Lower Limb Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_04_1783046728513.webp",
  },
  {
    name: "Mia Bergstrom",
    nationality: "Sweden",
    age: 37,
    role: "Physiotherapist",
    specialty: "Manual Therapy & Recovery",
    salary: 130000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Physiotherapy",
    personality: "Developer",
    attributes: { manipulation: 92, rehabilitation: 87, recovery: 91, injuryAssessment: 86 },
    specialTrait: "Hands of Gold",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_05_1783046741537.webp",
  },
  {
    name: "Sakura Yamamoto",
    nationality: "Japan",
    age: 44,
    role: "Physiotherapist",
    specialty: "Sports Taping & Injury Prevention",
    salary: 122000,
    skillLevel: 84,
    overallRating: 84,
    coachSpeciality: "Physiotherapy",
    personality: "Tactician",
    attributes: { manipulation: 86, rehabilitation: 84, recovery: 88, injuryAssessment: 87 },
    specialTrait: "Taping Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_06_1783046758353.webp",
  },
  {
    name: "Fatou Ndiaye",
    nationality: "Senegal",
    age: 32,
    role: "Physiotherapist",
    specialty: "Shoulder & Upper Body Rehab",
    salary: 113000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Physiotherapy",
    personality: "Developer",
    attributes: { manipulation: 82, rehabilitation: 83, recovery: 80, injuryAssessment: 81 },
    specialTrait: "Shoulder Saviour",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_07_1783047346503.webp",
  },
  {
    name: "Elena Vasquez",
    nationality: "Colombia",
    age: 28,
    role: "Physiotherapist",
    specialty: "Aquatic Therapy & Hydrotherapy",
    salary: 102000,
    skillLevel: 76,
    overallRating: 76,
    coachSpeciality: "Physiotherapy",
    personality: "Developer",
    attributes: { manipulation: 78, rehabilitation: 80, recovery: 82, injuryAssessment: 75 },
    specialTrait: "Aqua Therapy",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_08_1783047358048.webp",
  },
  {
    name: "Grace Okonkwo",
    nationality: "Kenya",
    age: 34,
    role: "Physiotherapist",
    specialty: "Sports Massage & Soft Tissue",
    salary: 95000,
    skillLevel: 72,
    overallRating: 72,
    coachSpeciality: "Physiotherapy",
    personality: "Motivator",
    attributes: { manipulation: 76, rehabilitation: 74, recovery: 78, injuryAssessment: 72 },
    specialTrait: "Soft Tissue Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_physiotherapist_09_1783047369288.webp",
  },
];

// ─── MEDICAL NUTRITIONISTS ────────────────────────────────────────────────────
const MEDICAL_NUTRITIONISTS: StaffDef[] = [
  {
    name: "Dr. Keiko Matsuda",
    nationality: "Japan",
    age: 40,
    role: "Nutritionist",
    specialty: "High-Performance Nutrition",
    salary: 128000,
    skillLevel: 92,
    overallRating: 92,
    coachSpeciality: "Nutrition",
    personality: "Tactician",
    attributes: { nutritionPlanning: 95, dietaryAnalysis: 93, supplementation: 89, recoveryNutrition: 92 },
    specialTrait: "Peak Fuel Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_01_1783379367790.webp",
  },
  {
    name: "Chiara Bianchi",
    nationality: "Italy",
    age: 35,
    role: "Nutritionist",
    specialty: "Mediterranean Performance Diet",
    salary: 115000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Nutrition",
    personality: "Developer",
    attributes: { nutritionPlanning: 90, dietaryAnalysis: 88, supplementation: 84, recoveryNutrition: 88 },
    specialTrait: "Anti-Inflammatory Diet",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_02_1783379378780.webp",
  },
  {
    name: "Aisha Mbeki",
    nationality: "South Africa",
    age: 38,
    role: "Nutritionist",
    specialty: "Body Composition & Weight Management",
    salary: 108000,
    skillLevel: 84,
    overallRating: 84,
    coachSpeciality: "Nutrition",
    personality: "Disciplinarian",
    attributes: { nutritionPlanning: 87, dietaryAnalysis: 90, supplementation: 82, recoveryNutrition: 85 },
    specialTrait: "Body Comp Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_03_1783379395117.webp",
  },
  {
    name: "Katarina Novak",
    nationality: "Slovakia",
    age: 43,
    role: "Nutritionist",
    specialty: "Sports Supplementation",
    salary: 120000,
    skillLevel: 88,
    overallRating: 88,
    coachSpeciality: "Nutrition",
    personality: "Tactician",
    attributes: { nutritionPlanning: 88, dietaryAnalysis: 85, supplementation: 95, recoveryNutrition: 87 },
    specialTrait: "Supplement Guru",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_04_1783379397634.webp",
  },
  {
    name: "Nina Torres",
    nationality: "Argentina",
    age: 31,
    role: "Nutritionist",
    specialty: "Plant-Based Athletic Nutrition",
    salary: 98000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Nutrition",
    personality: "Developer",
    attributes: { nutritionPlanning: 83, dietaryAnalysis: 86, supplementation: 78, recoveryNutrition: 84 },
    specialTrait: "Plant Power",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_05_1783379400886.webp",
  },
  {
    name: "Rachel Kim",
    nationality: "South Korea",
    age: 36,
    role: "Nutritionist",
    specialty: "Hydration & Electrolyte Balance",
    salary: 105000,
    skillLevel: 82,
    overallRating: 82,
    coachSpeciality: "Nutrition",
    personality: "Tactician",
    attributes: { nutritionPlanning: 84, dietaryAnalysis: 83, supplementation: 80, recoveryNutrition: 88 },
    specialTrait: "Hydration Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_06_1783379418084.webp",
  },
  {
    name: "Léa Fontaine",
    nationality: "France",
    age: 29,
    role: "Nutritionist",
    specialty: "Pre & Post Match Fuelling",
    salary: 92000,
    skillLevel: 77,
    overallRating: 77,
    coachSpeciality: "Nutrition",
    personality: "Developer",
    attributes: { nutritionPlanning: 80, dietaryAnalysis: 79, supplementation: 76, recoveryNutrition: 86 },
    specialTrait: "Match Fueller",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_07_1783379420346.webp",
  },
  {
    name: "Olga Petrenko",
    nationality: "Ukraine",
    age: 47,
    role: "Nutritionist",
    specialty: "Long-Term Athlete Health",
    salary: 110000,
    skillLevel: 85,
    overallRating: 85,
    coachSpeciality: "Nutrition",
    personality: "Developer",
    attributes: { nutritionPlanning: 87, dietaryAnalysis: 88, supplementation: 83, recoveryNutrition: 86 },
    specialTrait: "Longevity Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_08_1783379423102.webp",
  },
  {
    name: "Zainab Hassan",
    nationality: "Morocco",
    age: 34,
    role: "Nutritionist",
    specialty: "Gut Health & Microbiome",
    salary: 95000,
    skillLevel: 78,
    overallRating: 78,
    coachSpeciality: "Nutrition",
    personality: "Tactician",
    attributes: { nutritionPlanning: 80, dietaryAnalysis: 82, supplementation: 77, recoveryNutrition: 81 },
    specialTrait: "Gut Health Guru",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_09_1783379425115.webp",
  },
  {
    name: "Carla Santos",
    nationality: "Brazil",
    age: 52,
    role: "Nutritionist",
    specialty: "Clinical Sports Nutrition",
    salary: 87000,
    skillLevel: 74,
    overallRating: 74,
    coachSpeciality: "Nutrition",
    personality: "Developer",
    attributes: { nutritionPlanning: 76, dietaryAnalysis: 78, supplementation: 72, recoveryNutrition: 79 },
    specialTrait: "Clinical Nutritionist",
    scoutingRating: 50,
    imageFile: "staff_medical_nutritionist_10_1783379427382.webp",
  },
];

// ─── MEDICAL SCIENCE (images: 01,02,04,06,07,08,09,10) ───────────────────────
const MEDICAL_SCIENCE: StaffDef[] = [
  {
    name: "Dr. Ren Zhang",
    nationality: "China",
    age: 38,
    role: "Sports Scientist",
    specialty: "Biomechanics & Motion Analysis",
    salary: 148000,
    skillLevel: 93,
    overallRating: 93,
    coachSpeciality: "Science",
    personality: "Tactician",
    attributes: { dataAnalysis: 95, performanceTesting: 92, research: 94, biomechanics: 97 },
    specialTrait: "Motion Master",
    scoutingRating: 50,
    imageFile: "staff_medical_science_01_1783379538768.webp",
  },
  {
    name: "Sven Lindqvist",
    nationality: "Sweden",
    age: 44,
    role: "Sports Scientist",
    specialty: "Performance Data Analytics",
    salary: 138000,
    skillLevel: 89,
    overallRating: 89,
    coachSpeciality: "Science",
    personality: "Tactician",
    attributes: { dataAnalysis: 96, performanceTesting: 90, research: 88, biomechanics: 85 },
    specialTrait: "Data Wizard",
    scoutingRating: 50,
    imageFile: "staff_medical_science_02_1783379540945.webp",
  },
  {
    name: "Dr. Amelia Grant",
    nationality: "United Kingdom",
    age: 41,
    role: "Sports Scientist",
    specialty: "Exercise Physiology",
    salary: 132000,
    skillLevel: 86,
    overallRating: 86,
    coachSpeciality: "Science",
    personality: "Developer",
    attributes: { dataAnalysis: 88, performanceTesting: 90, research: 87, biomechanics: 84 },
    specialTrait: "Physiology Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_science_04_1783379545086.webp",
  },
  {
    name: "Paulo Ferreira",
    nationality: "Portugal",
    age: 36,
    role: "Sports Scientist",
    specialty: "GPS & Wearable Tech Analysis",
    salary: 125000,
    skillLevel: 83,
    overallRating: 83,
    coachSpeciality: "Science",
    personality: "Tactician",
    attributes: { dataAnalysis: 92, performanceTesting: 88, research: 80, biomechanics: 82 },
    specialTrait: "Tech Analyst",
    scoutingRating: 50,
    imageFile: "staff_medical_science_06_1783379550059.webp",
  },
  {
    name: "Dr. Fatima Ouédraogo",
    nationality: "Burkina Faso",
    age: 33,
    role: "Sports Scientist",
    specialty: "Heat Stress & Environmental Physiology",
    salary: 118000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Science",
    personality: "Developer",
    attributes: { dataAnalysis: 82, performanceTesting: 85, research: 84, biomechanics: 78 },
    specialTrait: "Environmental Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_science_07_1783379552749.webp",
  },
  {
    name: "Marcus Okafor",
    nationality: "Nigeria",
    age: 47,
    role: "Sports Scientist",
    specialty: "Strength & Power Science",
    salary: 110000,
    skillLevel: 77,
    overallRating: 77,
    coachSpeciality: "Science",
    personality: "Disciplinarian",
    attributes: { dataAnalysis: 80, performanceTesting: 82, research: 78, biomechanics: 76 },
    specialTrait: "Power Researcher",
    scoutingRating: 50,
    imageFile: "staff_medical_science_08_1783379555242.webp",
  },
  {
    name: "Yuki Mori",
    nationality: "Japan",
    age: 29,
    role: "Sports Scientist",
    specialty: "Sleep Science & Recovery Optimisation",
    salary: 104000,
    skillLevel: 74,
    overallRating: 74,
    coachSpeciality: "Science",
    personality: "Developer",
    attributes: { dataAnalysis: 76, performanceTesting: 75, research: 80, biomechanics: 72 },
    specialTrait: "Sleep Optimizer",
    scoutingRating: 50,
    imageFile: "staff_medical_science_09_1783379558009.webp",
  },
  {
    name: "Alicia Moreau",
    nationality: "Canada",
    age: 52,
    role: "Sports Scientist",
    specialty: "Altitude Training & VO2 Max",
    salary: 98000,
    skillLevel: 71,
    overallRating: 71,
    coachSpeciality: "Science",
    personality: "Tactician",
    attributes: { dataAnalysis: 73, performanceTesting: 76, research: 77, biomechanics: 70 },
    specialTrait: "Altitude Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_science_10_1783379559958.webp",
  },
];

// ─── MEDICAL SPECIALISTS ─────────────────────────────────────────────────────
const MEDICAL_SPECIALISTS: StaffDef[] = [
  {
    name: "Daniel Thompson",
    nationality: "Australia",
    age: 41,
    role: "Medical Specialist",
    specialty: "Sports Injury & Rehabilitation Expert",
    salary: 162500,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 88, rehabilitation: 92, research: 78, morale: 84 },
    specialTrait: "Orthopaedic Expert",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_01_1783379701681.webp",
  },
  {
    name: "Sofia Martinez",
    nationality: "Spain",
    age: 27,
    role: "Medical Specialist",
    specialty: "Performance Analyst",
    salary: 94000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 74, rehabilitation: 76, research: 90, morale: 86 },
    specialTrait: "Sports Scientist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_02_1783379698691.webp",
  },
  {
    name: "Meera Kapoor",
    nationality: "India",
    age: 53,
    role: "Medical Specialist",
    specialty: "Team Doctor",
    salary: 218000,
    skillLevel: 95,
    overallRating: 95,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 98, rehabilitation: 95, research: 86, morale: 91 },
    specialTrait: "Neck Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_03_1783379704251.webp",
  },
  {
    name: "Andrew Wilson",
    nationality: "Australia",
    age: 45,
    role: "Medical Specialist",
    specialty: "Team Doctor",
    salary: 182000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 95, rehabilitation: 93, research: 80, morale: 90 },
    specialTrait: "Knee Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_04_1783379706312.webp",
  },
  {
    name: "Benjamin Harris",
    nationality: "United Kingdom",
    age: 50,
    role: "Medical Specialist",
    specialty: "Team Doctor",
    salary: 176000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 93, rehabilitation: 92, research: 79, morale: 88 },
    specialTrait: "Hand Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_05_1783379799475.webp",
  },
  {
    name: "David Thompson",
    nationality: "Canada",
    age: 46,
    role: "Medical Specialist",
    specialty: "Team Doctor",
    salary: 171000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 92, rehabilitation: 94, research: 82, morale: 87 },
    specialTrait: "Ankle Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_06_1783379711647.webp",
  },
  {
    name: "Sarah Mitchell",
    nationality: "Australia",
    age: 48,
    role: "Medical Specialist",
    specialty: "Team Doctor",
    salary: 180000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 94, rehabilitation: 92, research: 83, morale: 89 },
    specialTrait: "Shoulder Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_07_1783379714051.webp",
  },
  {
    name: "James Carter",
    nationality: "United Kingdom",
    age: 52,
    role: "Medical Specialist",
    specialty: "Team Doctor",
    salary: 185000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 95, rehabilitation: 95, research: 81, morale: 90 },
    specialTrait: "Back Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_08_1783379716755.webp",
  },
  {
    name: "Nathaniel Goodwin",
    nationality: "New Zealand",
    age: 46,
    role: "Medical Specialist",
    specialty: "Brain & Nervous System Expert",
    salary: 214000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Tactician",
    attributes: { diagnosis: 97, rehabilitation: 91, research: 90, morale: 88 },
    specialTrait: "Neurology Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_09_1783379847734.webp",
  },
  {
    name: "Alessandro Rossi",
    nationality: "Italy",
    age: 35,
    role: "Medical Specialist",
    specialty: "Heart Health & Performance Medicine",
    salary: 168000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Medical",
    personality: "Developer",
    attributes: { diagnosis: 90, rehabilitation: 84, research: 91, morale: 87 },
    specialTrait: "Cardiology Specialist",
    scoutingRating: 50,
    imageFile: "staff_medical_specialist_10_1783379845033.webp",
  },
];

// ─── MASSAGE THERAPISTS ───────────────────────────────────────────────────────
const MASSAGE_THERAPISTS: StaffDef[] = [
  {
    name: "Yuki Hashimoto",
    nationality: "Japan",
    age: 34,
    role: "Massage Therapist",
    specialty: "Sports Massage & Deep Tissue",
    salary: 78000,
    skillLevel: 90,
    overallRating: 90,
    coachSpeciality: "Massage",
    personality: "Developer",
    attributes: { deepTissueMassage: 95, sportsMassage: 93, recovery: 91, injuryPrevention: 88 },
    specialTrait: "Deep Tissue Master",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_01_1783385525491.webp",
  },
  {
    name: "Camille Dupont",
    nationality: "France",
    age: 28,
    role: "Massage Therapist",
    specialty: "Relaxation & Recovery Massage",
    salary: 68000,
    skillLevel: 82,
    overallRating: 82,
    coachSpeciality: "Massage",
    personality: "Motivator",
    attributes: { deepTissueMassage: 84, sportsMassage: 88, recovery: 92, injuryPrevention: 82 },
    specialTrait: "Recovery Ace",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_02_1783385527725.webp",
  },
  {
    name: "Amira Osman",
    nationality: "Sudan",
    age: 37,
    role: "Massage Therapist",
    specialty: "Thai Sports Massage",
    salary: 72000,
    skillLevel: 85,
    overallRating: 85,
    coachSpeciality: "Massage",
    personality: "Developer",
    attributes: { deepTissueMassage: 88, sportsMassage: 92, recovery: 87, injuryPrevention: 85 },
    specialTrait: "Flexibility Focus",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_03_1783385530225.webp",
  },
  {
    name: "Nkechi Eze",
    nationality: "Nigeria",
    age: 31,
    role: "Massage Therapist",
    specialty: "Trigger Point & Myofascial Release",
    salary: 75000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Massage",
    personality: "Tactician",
    attributes: { deepTissueMassage: 90, sportsMassage: 89, recovery: 88, injuryPrevention: 90 },
    specialTrait: "Pain Relief Specialist",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_04_1783385642163.webp",
  },
  {
    name: "Lena Bauer",
    nationality: "Germany",
    age: 39,
    role: "Massage Therapist",
    specialty: "Lymphatic Drainage & Recovery",
    salary: 70000,
    skillLevel: 83,
    overallRating: 83,
    coachSpeciality: "Massage",
    personality: "Developer",
    attributes: { deepTissueMassage: 85, sportsMassage: 86, recovery: 90, injuryPrevention: 84 },
    specialTrait: "Inflammation Reducer",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_05_1783385535673.webp",
  },
  {
    name: "Maya Patel",
    nationality: "India",
    age: 26,
    role: "Massage Therapist",
    specialty: "Ayurvedic Sports Massage",
    salary: 63000,
    skillLevel: 78,
    overallRating: 78,
    coachSpeciality: "Massage",
    personality: "Developer",
    attributes: { deepTissueMassage: 80, sportsMassage: 82, recovery: 85, injuryPrevention: 79 },
    specialTrait: "Holistic Touch",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_06_1783385538127.webp",
  },
  {
    name: "Ingrid Svensson",
    nationality: "Norway",
    age: 43,
    role: "Massage Therapist",
    specialty: "Cold & Heat Therapy Massage",
    salary: 66000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Massage",
    personality: "Tactician",
    attributes: { deepTissueMassage: 83, sportsMassage: 84, recovery: 88, injuryPrevention: 82 },
    specialTrait: "Thermal Therapy",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_07_1783385540197.webp",
  },
  {
    name: "Rosa Gutierrez",
    nationality: "Peru",
    age: 33,
    role: "Massage Therapist",
    specialty: "Pre-Match Activation Massage",
    salary: 61000,
    skillLevel: 76,
    overallRating: 76,
    coachSpeciality: "Massage",
    personality: "Motivator",
    attributes: { deepTissueMassage: 78, sportsMassage: 81, recovery: 80, injuryPrevention: 77 },
    specialTrait: "Activation Specialist",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_08_1783385542622.webp",
  },
  {
    name: "Ji-Yeon Park",
    nationality: "South Korea",
    age: 30,
    role: "Massage Therapist",
    specialty: "Acupressure & Meridian Therapy",
    salary: 67000,
    skillLevel: 81,
    overallRating: 81,
    coachSpeciality: "Massage",
    personality: "Tactician",
    attributes: { deepTissueMassage: 82, sportsMassage: 85, recovery: 87, injuryPrevention: 83 },
    specialTrait: "Energy Flow Expert",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_09_1783385544706.webp",
  },
  {
    name: "Daniela Ferreira",
    nationality: "Brazil",
    age: 48,
    role: "Massage Therapist",
    specialty: "Structural Integration & Fascia",
    salary: 58000,
    skillLevel: 73,
    overallRating: 73,
    coachSpeciality: "Massage",
    personality: "Developer",
    attributes: { deepTissueMassage: 75, sportsMassage: 78, recovery: 80, injuryPrevention: 76 },
    specialTrait: "Fascia Specialist",
    scoutingRating: 50,
    imageFile: "staff_massage_therapist_10_1783385546966.webp",
  },
];

// ─── SCOUTS ───────────────────────────────────────────────────────────────────
const SCOUTS: StaffDef[] = [
  {
    name: "Marco Vieira",
    nationality: "Brazil",
    age: 45,
    role: "Scout",
    specialty: "South American Talent Network",
    salary: 92000,
    skillLevel: 90,
    overallRating: 90,
    coachSpeciality: "Scouting",
    personality: "Tactician",
    attributes: { talentIdentification: 95, dataAnalysis: 88, networking: 93, reportWriting: 85 },
    specialTrait: "South America Expert",
    scoutingRating: 93,
    imageFile: "staff_scouts_01_1783386795061.webp",
  },
  {
    name: "Hana Suzuki",
    nationality: "Japan",
    age: 38,
    role: "Scout",
    specialty: "Asian Youth Scouting",
    salary: 85000,
    skillLevel: 86,
    overallRating: 86,
    coachSpeciality: "Scouting",
    personality: "Developer",
    attributes: { talentIdentification: 90, dataAnalysis: 91, networking: 87, reportWriting: 88 },
    specialTrait: "Data-Driven Scout",
    scoutingRating: 89,
    imageFile: "staff_scouts_02_1783386805619.webp",
  },
  {
    name: "Viktor Kozlov",
    nationality: "Russia",
    age: 52,
    role: "Scout",
    specialty: "European Circuit Scouting",
    salary: 88000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Scouting",
    personality: "Tactician",
    attributes: { talentIdentification: 88, dataAnalysis: 86, networking: 92, reportWriting: 84 },
    specialTrait: "European Network",
    scoutingRating: 90,
    imageFile: "staff_scouts_03_1783386816013.webp",
  },
  {
    name: "Chioma Obi",
    nationality: "Nigeria",
    age: 36,
    role: "Scout",
    specialty: "African Beach Volleyball Talent",
    salary: 78000,
    skillLevel: 84,
    overallRating: 84,
    coachSpeciality: "Scouting",
    personality: "Developer",
    attributes: { talentIdentification: 87, dataAnalysis: 82, networking: 90, reportWriting: 80 },
    specialTrait: "African Region Specialist",
    scoutingRating: 87,
    imageFile: "staff_scouts_04_1783387127598.webp",
  },
  {
    name: "Sandra Kowalski",
    nationality: "Poland",
    age: 41,
    role: "Scout",
    specialty: "Video & Digital Scouting",
    salary: 82000,
    skillLevel: 85,
    overallRating: 85,
    coachSpeciality: "Scouting",
    personality: "Tactician",
    attributes: { talentIdentification: 86, dataAnalysis: 94, networking: 80, reportWriting: 90 },
    specialTrait: "Video Scout",
    scoutingRating: 88,
    imageFile: "staff_scouts_05_1783387138462.webp",
  },
  {
    name: "Ahmad Khoury",
    nationality: "Lebanon",
    age: 44,
    role: "Scout",
    specialty: "Middle East & North Africa Scouting",
    salary: 75000,
    skillLevel: 81,
    overallRating: 81,
    coachSpeciality: "Scouting",
    personality: "Developer",
    attributes: { talentIdentification: 83, dataAnalysis: 80, networking: 88, reportWriting: 78 },
    specialTrait: "MENA Specialist",
    scoutingRating: 84,
    imageFile: "staff_scouts_06_1783387145717.webp",
  },
  {
    name: "Rachel Thompson",
    nationality: "Australia",
    age: 33,
    role: "Scout",
    specialty: "Oceania & Pacific Rim Scouting",
    salary: 72000,
    skillLevel: 78,
    overallRating: 78,
    coachSpeciality: "Scouting",
    personality: "Motivator",
    attributes: { talentIdentification: 80, dataAnalysis: 78, networking: 85, reportWriting: 76 },
    specialTrait: "Oceania Expert",
    scoutingRating: 81,
    imageFile: "staff_scouts_07_1783387156727.webp",
  },
  {
    name: "Emeka Nwosu",
    nationality: "Ghana",
    age: 39,
    role: "Scout",
    specialty: "Youth Academy Identification",
    salary: 68000,
    skillLevel: 75,
    overallRating: 75,
    coachSpeciality: "Scouting",
    personality: "Developer",
    attributes: { talentIdentification: 84, dataAnalysis: 74, networking: 78, reportWriting: 72 },
    specialTrait: "Youth Identifier",
    scoutingRating: 78,
    imageFile: "staff_scouts_08_1783387164207.webp",
  },
  {
    name: "Maria González",
    nationality: "Mexico",
    age: 29,
    role: "Scout",
    specialty: "Central & North American Circuit",
    salary: 64000,
    skillLevel: 71,
    overallRating: 71,
    coachSpeciality: "Scouting",
    personality: "Developer",
    attributes: { talentIdentification: 74, dataAnalysis: 73, networking: 76, reportWriting: 70 },
    specialTrait: "Americas Scout",
    scoutingRating: 74,
    imageFile: "staff_scouts_09_1783387174352.webp",
  },
  {
    name: "Pete Harrison",
    nationality: "New Zealand",
    age: 58,
    role: "Scout",
    specialty: "General Talent Assessment",
    salary: 58000,
    skillLevel: 65,
    overallRating: 65,
    coachSpeciality: "Scouting",
    personality: "Motivator",
    attributes: { talentIdentification: 68, dataAnalysis: 64, networking: 72, reportWriting: 66 },
    specialTrait: "Veteran Scout",
    scoutingRating: 68,
    imageFile: "staff_scouts_10_1783387181847.webp",
  },
];

// ─── PROMOTIONAL MANAGERS ─────────────────────────────────────────────────────
const PROMOTIONAL_MANAGERS: StaffDef[] = [
  {
    name: "Victoria Chen",
    nationality: "Singapore",
    age: 38,
    role: "Promotional Manager",
    specialty: "Global Brand Partnerships",
    salary: 118000,
    skillLevel: 92,
    overallRating: 92,
    coachSpeciality: "Marketing",
    personality: "Motivator",
    attributes: { marketing: 95, eventManagement: 88, partnerships: 96, mediaRelations: 91 },
    specialTrait: "Brand Builder",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_01_1783386379759.webp",
  },
  {
    name: "James Okafor",
    nationality: "Nigeria",
    age: 44,
    role: "Promotional Manager",
    specialty: "Social Media & Digital Marketing",
    salary: 105000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Marketing",
    personality: "Developer",
    attributes: { marketing: 92, eventManagement: 82, partnerships: 88, mediaRelations: 94 },
    specialTrait: "Digital Influencer",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_02_1783386385281.webp",
  },
  {
    name: "Isabelle Laurent",
    nationality: "France",
    age: 35,
    role: "Promotional Manager",
    specialty: "Event Management & Fan Experience",
    salary: 98000,
    skillLevel: 84,
    overallRating: 84,
    coachSpeciality: "Marketing",
    personality: "Motivator",
    attributes: { marketing: 85, eventManagement: 96, partnerships: 85, mediaRelations: 87 },
    specialTrait: "Event Maestro",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_03_1783386389823.webp",
  },
  {
    name: "Ryan Park",
    nationality: "South Korea",
    age: 31,
    role: "Promotional Manager",
    specialty: "Merchandise & Commercial Revenue",
    salary: 95000,
    skillLevel: 82,
    overallRating: 82,
    coachSpeciality: "Marketing",
    personality: "Tactician",
    attributes: { marketing: 88, eventManagement: 80, partnerships: 90, mediaRelations: 82 },
    specialTrait: "Revenue Generator",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_04_1783386410327.webp",
  },
  {
    name: "Amina Traore",
    nationality: "Ivory Coast",
    age: 29,
    role: "Promotional Manager",
    specialty: "Community Engagement & Grassroots",
    salary: 82000,
    skillLevel: 78,
    overallRating: 78,
    coachSpeciality: "Marketing",
    personality: "Motivator",
    attributes: { marketing: 80, eventManagement: 85, partnerships: 78, mediaRelations: 82 },
    specialTrait: "Community Builder",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_05_1783386414785.webp",
  },
  {
    name: "Lucas Hartmann",
    nationality: "Germany",
    age: 46,
    role: "Promotional Manager",
    specialty: "Sponsorship Acquisition",
    salary: 110000,
    skillLevel: 86,
    overallRating: 86,
    coachSpeciality: "Marketing",
    personality: "Tactician",
    attributes: { marketing: 87, eventManagement: 83, partnerships: 95, mediaRelations: 86 },
    specialTrait: "Sponsorship King",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_06_1783386418414.webp",
  },
  {
    name: "Priya Sharma",
    nationality: "India",
    age: 33,
    role: "Promotional Manager",
    specialty: "PR & Media Relations",
    salary: 88000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Marketing",
    personality: "Motivator",
    attributes: { marketing: 82, eventManagement: 78, partnerships: 80, mediaRelations: 94 },
    specialTrait: "Media Queen",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_07_1783386421444.webp",
  },
  {
    name: "Carlos Rueda",
    nationality: "Colombia",
    age: 40,
    role: "Promotional Manager",
    specialty: "Stadium Operations & Fan Zones",
    salary: 76000,
    skillLevel: 74,
    overallRating: 74,
    coachSpeciality: "Marketing",
    personality: "Developer",
    attributes: { marketing: 76, eventManagement: 88, partnerships: 72, mediaRelations: 74 },
    specialTrait: "Stadium Expert",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_08_1783386424440.webp",
  },
  {
    name: "Fiona Walsh",
    nationality: "Ireland",
    age: 27,
    role: "Promotional Manager",
    specialty: "Content Creation & Broadcasting",
    salary: 70000,
    skillLevel: 70,
    overallRating: 70,
    coachSpeciality: "Marketing",
    personality: "Developer",
    attributes: { marketing: 78, eventManagement: 70, partnerships: 68, mediaRelations: 88 },
    specialTrait: "Content Creator",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_09_1783386427684.webp",
  },
  {
    name: "Henri Fontaine",
    nationality: "Belgium",
    age: 54,
    role: "Promotional Manager",
    specialty: "Corporate Hospitality & VIP Relations",
    salary: 92000,
    skillLevel: 83,
    overallRating: 83,
    coachSpeciality: "Marketing",
    personality: "Motivator",
    attributes: { marketing: 82, eventManagement: 86, partnerships: 90, mediaRelations: 80 },
    specialTrait: "VIP Specialist",
    scoutingRating: 50,
    imageFile: "staff_promotional_manager_10_1783386431103.webp",
  },
];

// ─── STRENGTH & CONDITIONING COACHES ─────────────────────────────────────────
const STRENGTH_CONDITIONERS: StaffDef[] = [
  {
    name: "Jake Morrison",
    nationality: "United States",
    age: 42,
    role: "Strength Coach",
    specialty: "Olympic Weightlifting & Power",
    salary: 108000,
    skillLevel: 93,
    overallRating: 93,
    coachSpeciality: "Strength",
    personality: "Disciplinarian",
    attributes: { strengthTraining: 97, conditioning: 90, powerDevelopment: 96, endurance: 85 },
    specialTrait: "Power Maximiser",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_01_1783386598159.webp",
  },
  {
    name: "Elena Marchetti",
    nationality: "Italy",
    age: 36,
    role: "Strength Coach",
    specialty: "Functional Strength & Movement",
    salary: 96000,
    skillLevel: 88,
    overallRating: 88,
    coachSpeciality: "Strength",
    personality: "Developer",
    attributes: { strengthTraining: 91, conditioning: 88, powerDevelopment: 89, endurance: 87 },
    specialTrait: "Movement Efficiency",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_02_1783386614800.webp",
  },
  {
    name: "Koffi Mensah",
    nationality: "Ghana",
    age: 39,
    role: "Strength Coach",
    specialty: "Explosive Speed & Plyometrics",
    salary: 92000,
    skillLevel: 86,
    overallRating: 86,
    coachSpeciality: "Strength",
    personality: "Motivator",
    attributes: { strengthTraining: 87, conditioning: 91, powerDevelopment: 95, endurance: 88 },
    specialTrait: "Explosive Power",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_03_1783386622386.webp",
  },
  {
    name: "Sienna Clarke",
    nationality: "Australia",
    age: 33,
    role: "Strength Coach",
    specialty: "Periodisation & Season Planning",
    salary: 98000,
    skillLevel: 87,
    overallRating: 87,
    coachSpeciality: "Strength",
    personality: "Tactician",
    attributes: { strengthTraining: 89, conditioning: 94, powerDevelopment: 87, endurance: 92 },
    specialTrait: "Periodisation Expert",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_04_1783386632808.webp",
  },
  {
    name: "Dmitri Volkov",
    nationality: "Russia",
    age: 48,
    role: "Strength Coach",
    specialty: "Core Stability & Balance",
    salary: 88000,
    skillLevel: 84,
    overallRating: 84,
    coachSpeciality: "Strength",
    personality: "Disciplinarian",
    attributes: { strengthTraining: 88, conditioning: 86, powerDevelopment: 83, endurance: 89 },
    specialTrait: "Core Specialist",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_05_1783386644672.webp",
  },
  {
    name: "Thabo Dlamini",
    nationality: "South Africa",
    age: 35,
    role: "Strength Coach",
    specialty: "Sand Training & Resistance Work",
    salary: 82000,
    skillLevel: 81,
    overallRating: 81,
    coachSpeciality: "Strength",
    personality: "Developer",
    attributes: { strengthTraining: 85, conditioning: 88, powerDevelopment: 82, endurance: 86 },
    specialTrait: "Sand Training Guru",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_06_1783386653612.webp",
  },
  {
    name: "Ana Castillo",
    nationality: "Spain",
    age: 31,
    role: "Strength Coach",
    specialty: "Endurance & Stamina Building",
    salary: 78000,
    skillLevel: 78,
    overallRating: 78,
    coachSpeciality: "Strength",
    personality: "Motivator",
    attributes: { strengthTraining: 80, conditioning: 85, powerDevelopment: 76, endurance: 95 },
    specialTrait: "Stamina Builder",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_07_1783386663163.webp",
  },
  {
    name: "Riku Mäkinen",
    nationality: "Finland",
    age: 44,
    role: "Strength Coach",
    specialty: "Injury Resilience & Pre-habilitation",
    salary: 84000,
    skillLevel: 80,
    overallRating: 80,
    coachSpeciality: "Strength",
    personality: "Developer",
    attributes: { strengthTraining: 83, conditioning: 84, powerDevelopment: 78, endurance: 87 },
    specialTrait: "Injury Resilience",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_08_1783386672394.webp",
  },
  {
    name: "Mei Sun",
    nationality: "China",
    age: 29,
    role: "Strength Coach",
    specialty: "Agility & Reaction Speed",
    salary: 74000,
    skillLevel: 74,
    overallRating: 74,
    coachSpeciality: "Strength",
    personality: "Developer",
    attributes: { strengthTraining: 76, conditioning: 80, powerDevelopment: 78, endurance: 82 },
    specialTrait: "Reaction Trainer",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_09_1783386682293.webp",
  },
  {
    name: "Tom Bradley",
    nationality: "United Kingdom",
    age: 57,
    role: "Strength Coach",
    specialty: "General Conditioning & Veteran Management",
    salary: 68000,
    skillLevel: 69,
    overallRating: 69,
    coachSpeciality: "Strength",
    personality: "Motivator",
    attributes: { strengthTraining: 72, conditioning: 75, powerDevelopment: 68, endurance: 78 },
    specialTrait: "Veteran Conditioner",
    scoutingRating: 50,
    imageFile: "staff_strength_conditioner_10_1783386687670.webp",
  },
];

// ─── All staff batches ────────────────────────────────────────────────────────
interface StaffBatch {
  type: string;
  members: StaffDef[];
}

const ALL_BATCHES: StaffBatch[] = [
  { type: "head_coach", members: HEAD_COACHES },
  { type: "assistant_coach", members: ASSISTANT_COACHES },
  { type: "fitness_trainer", members: FITNESS_TRAINERS },
  { type: "medical_doctor", members: MEDICAL_DOCTORS },
  { type: "medical_physiotherapist", members: MEDICAL_PHYSIOTHERAPISTS },
  { type: "medical_nutritionist", members: MEDICAL_NUTRITIONISTS },
  { type: "medical_science", members: MEDICAL_SCIENCE },
  { type: "medical_specialist", members: MEDICAL_SPECIALISTS },
  { type: "massage_therapist", members: MASSAGE_THERAPISTS },
  { type: "scouts", members: SCOUTS },
  { type: "promotional_manager", members: PROMOTIONAL_MANAGERS },
  { type: "strength_conditioner", members: STRENGTH_CONDITIONERS },
];

async function main() {
  let totalInserted = 0;
  let totalUploaded = 0;

  for (const batch of ALL_BATCHES) {
    console.log(`\n=== ${batch.type.toUpperCase()} (${batch.members.length}) ===`);

    for (const [i, member] of batch.members.entries()) {
      console.log(`  [${i + 1}/${batch.members.length}] ${member.name} (${member.nationality})`);

      const entityId = `staff/${batch.type}/staff-${String(i + 1).padStart(2, "0")}.webp`;
      const localPath = resolve(WORKSPACE_ROOT, "attached_assets", member.imageFile);

      let imageUrl: string | null = null;
      try {
        imageUrl = await uploadImage(localPath, entityId);
        totalUploaded++;
      } catch (err) {
        console.error(`    ERROR uploading image: ${err}`);
      }

      await db.insert(staffTable).values({
        name: member.name,
        nationality: member.nationality,
        age: member.age,
        role: member.role,
        specialty: member.specialty,
        salary: String(member.salary),
        skillLevel: member.skillLevel,
        overallRating: member.overallRating,
        teamId: null,
        isAvailable: true,
        coachSpeciality: member.coachSpeciality,
        personality: member.personality,
        attributes: member.attributes,
        specialTrait: member.specialTrait,
        scoutingRating: member.scoutingRating,
        contractLength: 12,
        imageUrl,
      });

      totalInserted++;
      console.log(`    inserted → imageUrl=${imageUrl}`);
    }
  }

  console.log(`\n=== Done! ${totalInserted} staff seeded, ${totalUploaded} images uploaded. ===`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
