/**
 * Phase 7 invariant sweep — partial baseline.
 *
 * The spec is explicit that only the FULL phase-7 numbers count: measuring nine
 * invariants at nine different points in a moving codebase and calling it nine
 * passes is not a pass. This run is therefore deliberately split:
 *
 *   GROUP A — measurable today. Real results. I7 is a PHASE 0 acceptance test
 *     (the engines were unified in phase 0), so a failure there is a bug to fix
 *     now, not a future-phase gap. I1/I3/I4 are recorded as the pre-economy
 *     BASELINE that phases 2-4 get judged against.
 *
 *   GROUP B — not measurable. Listed with the specific missing system and NOT
 *     run, so the reason each is absent is on the record rather than implied.
 *
 * Everything here calls the real shipped code. Nothing is re-implemented: an
 * earlier version of this project's economy modelling was a standalone
 * Math.random() script that never touched the server, and it was reported as a
 * measurement. It was not one.
 *
 * Usage: node harness/invariants.mjs
 */
import { spawnSync } from "node:child_process";
import path from "node:path";
import fs from "node:fs";

import { requireElectronBinary } from "./electron-binary.mjs";

const REPO = path.join(import.meta.dirname, "..");
const ELECTRON = requireElectronBinary(REPO);
const TSX = path.join(REPO, "node_modules", ".pnpm", "tsx@4.21.0",
  "node_modules", "tsx", "dist", "cli.mjs");

const NEWLINE = String.fromCharCode(10);
const bar = (c) => c.repeat(74);

let failures = 0;
const results = [];

function record(id, name, verdict, detail) {
  results.push({ id, name, verdict, detail });
  if (verdict === "FAIL") failures++;
  const tag = verdict === "PASS" ? "PASS" : verdict === "FAIL" ? "FAIL" : verdict;
  console.log(`  ${tag.padEnd(9)} ${id} ${name}`);
  for (const line of String(detail).split(NEWLINE)) console.log(`            ${line}`);
}

/**
 * Run a probe inside the api-server package, under Electron's node so the
 * native better-sqlite3 ABI matches, importing the REAL engine modules.
 */
function probe(source) {
  const file = path.join(REPO, "artifacts", "api-server", "src", `__probe_${Date.now()}.ts`);
  fs.writeFileSync(file, source);
  try {
    const r = spawnSync(ELECTRON, [TSX, file], {
      cwd: path.join(REPO, "artifacts", "api-server"),
      encoding: "utf8",
      env: { ...process.env, ELECTRON_RUN_AS_NODE: "1", DB_PATH: path.join(REPO, "lib", "db", "volleyball-empire.sqlite") },
    });
    if (r.status !== 0) {
      throw new Error(`probe failed (${r.status}):${NEWLINE}${r.stdout}${NEWLINE}${r.stderr}`);
    }
    const line = r.stdout.trim().split(NEWLINE).filter((l) => l.startsWith("{")).pop();
    if (!line) throw new Error(`probe produced no JSON:${NEWLINE}${r.stdout}${NEWLINE}${r.stderr}`);
    return JSON.parse(line);
  } finally {
    fs.rmSync(file, { force: true });
  }
}

console.log(NEWLINE + bar("="));
console.log("  PHASE 7 INVARIANT SWEEP — PARTIAL BASELINE");
console.log(bar("="));

// ── GROUP A ─────────────────────────────────────────────────────────────────
console.log(NEWLINE + "GROUP A — measurable today (real results)" + NEWLINE);

// I7 ONE ENGINE ──────────────────────────────────────────────────────────────
//
// The test: for the SAME rating gap, every simulation path must produce the
// same win probability. If the regional league's table is generated by
// different maths than the player's results, the league is fiction.
{
  const N = 20000;
  const data = probe(`
import { pointProbability, simulateMatch } from "./utils/matchEngine.js";
import { simulateFixtureResult } from "./utils/regionalSeason.js";

const GAPS = [0, 5, 10, 25];
const N = ${N};
const out: any = { shared: {}, regional: {} };

for (const gap of GAPS) {
  // pointProbability takes two RATINGS, not a diff. Passing a diff makes p NaN
  // and the home side never wins — which is exactly what the first version of
  // this probe reported, as 0.0% at every gap including a level match.
  //
  // homeAdvantage must match what the regional path passes, or the comparison
  // measures the modifier rather than the engine: the flat ~2pp gap the second
  // version showed at every gap was HOME_ADVANTAGE_RATING, not a divergence.
  const p = pointProbability(70 + gap, 70, { homeAdvantage: true });
  if (!Number.isFinite(p)) throw new Error("pointProbability returned " + p);
  let sharedWins = 0;
  for (let i = 0; i < N; i++) {
    if (simulateMatch(p).homeWon) sharedWins++;
  }
  out.shared[gap] = sharedWins / N;

  let regionalWins = 0;
  for (let i = 0; i < N; i++) {
    if (simulateFixtureResult(70 + gap, 70).winnerId === "home") regionalWins++;
  }
  out.regional[gap] = regionalWins / N;
}
console.log(JSON.stringify(out));
`);

  const rows = [];
  let maxDelta = 0;
  for (const gap of [0, 5, 10, 25]) {
    const a = data.shared[gap], b = data.regional[gap];
    const delta = Math.abs(a - b);
    maxDelta = Math.max(maxDelta, delta);
    rows.push(`gap +${String(gap).padStart(2)}:  shared ${(a * 100).toFixed(1)}%   regional ${(b * 100).toFixed(1)}%   delta ${(delta * 100).toFixed(1)}pp`);
  }
  // Both engines are stochastic; 2pp is comfortably outside sampling noise at
  // n=20000 (se ~0.35pp) while not being so tight it flags on jitter.
  const pass = maxDelta <= 0.02;
  record("I7", "ONE ENGINE", pass ? "PASS" : "FAIL",
    rows.join(NEWLINE) + NEWLINE +
    `max divergence ${(maxDelta * 100).toFixed(1)}pp (threshold 2.0pp)` + NEWLINE +
    `CAVEAT — the youth league is NOT covered by this and does not have a second` + NEWLINE +
    `engine; it has NO engine. AI academy ladder records are seeded from` + NEWLINE +
    `Math.random() and the championship is decided by a coin flip, with no squad` + NEWLINE +
    `rating involved anywhere. Wiring it to the shared engine needs AI academy` + NEWLINE +
    `strength to exist first, which is a design gap, not a refactor. Recorded in` + NEWLINE +
    `docs/economy-design.md as a Phase 1 requirement.`);
}

// I3 NO SINGLE-MATCH LOTTERY ────────────────────────────────────────────────
//
// Pure configuration analysis of the shipped schedule: no simulation involved,
// so this is a fact about what ships rather than a model of it.
{
  const d = probe(`
import { WORLD_TOUR } from "./data/worldTour.js";
const total = WORLD_TOUR.reduce((s, e) => s + e.prize, 0);
const biggest = WORLD_TOUR.reduce((a, b) => (b.prize > a.prize ? b : a));
const byTier: Record<string, { n: number; total: number }> = {};
for (const e of WORLD_TOUR) {
  byTier[e.tier] ??= { n: 0, total: 0 };
  byTier[e.tier]!.n++;
  byTier[e.tier]!.total += e.prize;
}
console.log(JSON.stringify({ events: WORLD_TOUR.length, total, biggest, byTier }));
`);
  const share = d.biggest.prize / d.total;
  const rows = Object.entries(d.byTier)
    .sort((a, b) => a[1].total - b[1].total)
    .map(([t, v]) => `  ${t.padEnd(14)} ${String(v.n).padStart(2)} events   $${v.total.toLocaleString()}`);
  record("I3", "NO SINGLE-MATCH LOTTERY", "BASELINE",
    [`${d.events} events, $${d.total.toLocaleString()} total achievable prize money`,
     ...rows,
     `biggest single: "${d.biggest.displayName}" $${d.biggest.prize.toLocaleString()} (${d.biggest.tier})`,
     `= ${(share * 100).toFixed(1)}% of the whole season   TARGET <= 15%   ${share <= 0.15 ? "within" : "VIOLATED"}`,
    ].join(NEWLINE));
}

// I1 MONOTONIC RETURN and I4 PREDICTABILITY ─────────────────────────────────
//
// Both run the REAL engine over the REAL shipped schedule with REAL squads
// drawn from the shipped database. What they cannot do is run a season through
// the server, because season rollover does not exist — so this is the engine
// and the prize table, not a played career. Stated plainly because an earlier
// version of this project's economy modelling was a standalone Math.random()
// script reported as a measurement, and it was not one.
{
  const RUNS = 5;
  const d = probe(`
import { WORLD_TOUR } from "./data/worldTour.js";
import { pointProbability, simulateMatch, sideRating, opponentRatingFromTier } from "./utils/matchEngine.js";
import { monthlyWage } from "./utils/wageCurve.js";
import { eligibilityFor, currentTier, PUSHED_OUT_PRIZE_MULTIPLIER } from "./utils/tierQualification.js";
import { prizeFor } from "./utils/prizeDistribution.js";
import { rankingPointsFor } from "./utils/rankingPoints.js";
import { db, playersTable } from "@workspace/db";

// Real athletes, ordered by what they cost.
const all = await db.select().from(playersTable);
const seniors = all
  .filter((p: any) => p.playerType === "senior" && p.askingPrice)
  .sort((a: any, b: any) => Number(a.askingPrice) - Number(b.askingPrice));

const pick = (from: number) => seniors.slice(from, from + 2);
const rate = (ps: any[]) => sideRating(ps.map((p: any) => ({
  speed: p.speed, power: p.power, defense: p.defense,
  serve: p.serve, block: p.block, stamina: p.stamina,
})));

/** The same athletes with attributes scaled so the side rating hits a target. */
const developed = (ps: any[], target: number) => {
  const k = target / rate(ps);
  return ps.map((p: any) => ({
    ...p,
    speed: p.speed * k, power: p.power * k, defense: p.defense * k,
    serve: p.serve * k, block: p.block * k, stamina: p.stamina * k,
  }));
};

const BEST = seniors.slice(-2);

// A FIFTH squad, and the only one that can reach Gold.
//
// The four purchasable squads are drawn from the shipped roster, so the
// strongest of them rates 76.3 and tops out around 38 ranking points against a
// Gold threshold of 40. Measuring tier access with a field that cannot cross the
// gate measures nothing: every squad lands in Silver by construction, and I5's
// "climbing pays" has no boundary to pay across.
//
// The arc's route to Gold is NOT accumulated ranking points - those reset every
// season. It is squad development: docs/economy-design.md models the Phase 1
// curve as 75.0 in season one rising to an 89.5 ceiling. So 'developed' is the
// SAME athletes as 'best', trained to that ceiling, on the SAME wages, because a
// contract does not re-price when a player improves. Season 3 so the opponents
// are at season-3 strength too - opponentRatingFromTier adds +2 rating a season
// and every other squad here is measured against season-1 opposition.
const SQUADS: Array<{ label: string; players: any[]; wageFrom: any[]; season: number }> = [
  { label: "cheapest",  players: pick(0), wageFrom: pick(0), season: 1 },
  { label: "lower-mid", players: pick(Math.floor(seniors.length * 0.33)), wageFrom: pick(Math.floor(seniors.length * 0.33)), season: 1 },
  { label: "upper-mid", players: pick(Math.floor(seniors.length * 0.66)), wageFrom: pick(Math.floor(seniors.length * 0.66)), season: 1 },
  { label: "best",      players: BEST, wageFrom: BEST, season: 1 },
  { label: "developed", players: developed(BEST, 89.5), wageFrom: BEST, season: 3 },
];

const out: any = { squads: [], runs: [] };

for (const squad of SQUADS) {
  const rating = rate(squad.players);
  // The REAL wage relation, imported rather than restated — a model that
  // recomputes the formula stops measuring the game the moment one of them moves.
  // Wages come from the SIGNED players, not the developed ratings: training a
  // player does not re-open his contract.
  const seasonWage = squad.wageFrom.reduce((s: number, p: any) => s + monthlyWage(p.askingPrice), 0) * 12;

  // A GATED season, walked in schedule order.
  //
  // This can no longer be a per-event expectation. Eligibility depends on
  // ranking points the club has actually banked BY THAT POINT in the season, so
  // whether an event can be entered at all depends on realised earlier results.
  // Averaging whole ordered seasons is the only way to measure that; averaging
  // per-event win probabilities would silently assume the club was eligible for
  // everything, which is the assumption the old model carried and gating exists
  // to remove.
  const schedule = [...WORLD_TOUR].sort((a: any, b: any) => a.round - b.round);
  const SEASONS = 200;
  const goldOnCard = schedule.filter((e: any) => e.tier === "Gold").length;
  let expected = 0, entered = 0, scored = 0, endPoints = 0, goldIn = 0;

  for (let run = 0; run < SEASONS; run++) {
    let points = 0, income = 0, n = 0, sc = 0, gold = 0;
    for (const e of schedule) {
      const elig = eligibilityFor(e.tier, points);
      // Below the threshold the club cannot enter at all. Above its band it may
      // enter for a token purse and no points (D4b).
      if (!elig.eligible) continue;
      n++;
      if (e.tier === "Gold") gold++;
      const opp = opponentRatingFromTier(e.tier, e.opponent, squad.season);
      const p = pointProbability(rating, opp, { homeAdvantage: false });
      const won = simulateMatch(p).homeWon;
      // Both finishers are paid — the split is imported, never restated here.
      income += prizeFor(e.prize, won, elig.scores ? 1 : PUSHED_OUT_PRIZE_MULTIPLIER);
      if (won && elig.scores) { points += rankingPointsFor(e.tier, true); sc++; }
    }
    expected += income; entered += n; scored += sc; endPoints += points; goldIn += gold;
  }

  expected /= SEASONS; entered /= SEASONS; scored /= SEASONS; endPoints /= SEASONS;
  goldIn /= SEASONS;
  out.squads.push({
    label: squad.label, rating, seasonWage, expected, net: expected - seasonWage,
    entered, scored, endPoints, tier: currentTier(endPoints),
    goldIn, goldOnCard, season: squad.season,
  });
}

// I4: the SAME squad, five independent stochastic runs of the whole schedule.
const fixed = SQUADS[2]!;
const fixedRating = sideRating(fixed.players.map((p: any) => ({
  speed: p.speed, power: p.power, defense: p.defense,
  serve: p.serve, block: p.block, stamina: p.stamina,
})));
for (let run = 0; run < ${RUNS}; run++) {
  let income = 0;
  for (const e of WORLD_TOUR) {
    const opp = opponentRatingFromTier(e.tier, e.opponent);
    const p = pointProbability(fixedRating, opp, { homeAdvantage: false });
    income += prizeFor(e.prize, simulateMatch(p).homeWon);
  }
  out.runs.push(income);
}
console.log(JSON.stringify(out));
process.exit(0);
`);

  const rows = d.squads.map((s) =>
    `  ${s.label.padEnd(10)} rating ${s.rating.toFixed(1).padStart(5)}   ` +
    `${s.tier.padEnd(6)} ${s.endPoints.toFixed(1).padStart(5)}pts   ` +
    `${s.entered.toFixed(0).padStart(2)} entered   ` +
    `wages $${Math.round(s.seasonWage).toLocaleString().padStart(9)}   ` +
    `net $${Math.round(s.net).toLocaleString().padStart(9)}   ` +
    `return ${(s.expected / s.seasonWage).toFixed(2)}x`);
  const ratios = d.squads.map((s) => s.expected / s.seasonWage);
  const monotonic = ratios.every((r, i) => i === 0 || r >= ratios[i - 1] - 1e-9);
  record("I1", "MONOTONIC RETURN", monotonic ? "PASS" : "VIOLATED",
    [...rows,
     `return multiple ${monotonic ? "rises" : "FALLS"} with squad quality` +
     `   (${ratios.map((r) => r.toFixed(2) + "x").join(" -> ")})`,
     `TARGET: a better squad must earn a better net result`,
     ``,
     `Phase 3 is DONE and did not fix this — as predicted, not as a surprise.`,
     `The purse re-scale and the runner-up split were aimed at I3 and I4 and`,
     `landed both (35.0% -> 11.8%, 41.5% -> 7.6%). Neither can move I1, and the`,
     `split works mildly AGAINST it: paying the loser compresses the income gap`,
     `between a strong squad and a weak one. See utils/prizeDistribution.ts.`,
     ``,
     `What is left is NOT a prize problem. Income already rises with quality;`,
     `wages just rise faster (cheapest -> best is 2.00x wages against 1.32x`,
     `income).`,
     ``,
     `TIER ACCESS IS NOT THE ANSWER EITHER — tested directly, 2026-09-01.`,
     `Granting Gold to EVERY squad from the first round (all 62 events enterable,`,
     `all 14 Gold events played) leaves the return still falling:`,
     `5.47x -> 3.74x -> 3.52x -> 3.09x. Equal access cannot separate squads, and`,
     `unequal access only separates the ENDS: the developed squad on Gold beats`,
     `cheapest on Silver, but cheapest still beats every squad between them.`,
     ``,
     `The surviving inversion is cheapest vs lower-mid, and BOTH sit in Silver`,
     `with identical access either way. It is a pricing relation, not a gate:`,
     `+52.7% wages ($132,000 -> $201,600) buys +9.6% income. Until a dollar of`,
     `wage buys more than that, no threshold setting can make I1 monotonic.`,
     `Do NOT lower the Gold threshold to chase this — it is not what is wrong.`,
    ].join(NEWLINE));

  // I5 — climbing pays. Unblocked by 2.1-2.3: there are tier boundaries now.
  const byTier = new Map();
  for (const s of d.squads) byTier.set(s.tier, [...(byTier.get(s.tier) ?? []), s]);
  const tiersReached = [...byTier.keys()];
  const i5rows = d.squads.map((s) =>
    `  ${s.label.padEnd(10)} reached ${s.tier.padEnd(6)} on ${s.endPoints.toFixed(1)} pts   ` +
    `${s.entered.toFixed(0)} entered / ${s.scored.toFixed(1)} scored   ` +
    `Gold ${s.goldIn.toFixed(1)}/${s.goldOnCard}   ` +
    `income $${Math.round(s.expected).toLocaleString()}`);
  if (tiersReached.length < 2) {
    record("I5", "CLIMBING PAYS", "VIOLATED",
      [...i5rows,
       ``,
       `All four squads finish in the SAME band (${tiersReached[0]}), so there is no`,
       `tier boundary between a ${d.squads[0].rating.toFixed(1)}-rated squad and a` +
       ` ${d.squads[d.squads.length - 1].rating.toFixed(1)}-rated one.`,
       `The gate is not separating them. That is a THRESHOLD question, not a`,
       `prize question: Silver 15 / Gold 40 were set to make Gold reachable`,
       `across the arc (I8), and the same setting makes it reachable by everyone`,
       `in season one. Needs re-tuning once Phase 3 fixes the purses.`,
      ].join(NEWLINE));
  } else {
    const order = ["Bronze", "Silver", "Gold"];
    const sorted = [...d.squads].sort((x, y) => order.indexOf(x.tier) - order.indexOf(y.tier));
    const pays = sorted.every((s, i) => i === 0 || s.expected >= sorted[i - 1].expected - 1e-9);
    record("I5", "CLIMBING PAYS", pays ? "PASS" : "VIOLATED",
      [...i5rows,
       ``,
       `${tiersReached.length} bands reached; income ${pays ? "rises" : "does NOT rise"} with tier.`,
       ``,
       `READ THE Gold COLUMN BEFORE BELIEVING THIS. Reaching Gold and PLAYING`,
       `Gold are not the same thing. Ranking resets every season, so a club`,
       `climbs from zero each year and crosses 40 points late — by which time`,
       `most of the 14 Gold events on the card have already been and gone. The`,
       `Gold tier holds 44.1% of the season's prize money and is entered a`,
       `fraction of a time per season even by a squad that clears the gate.`,
       `Qualifying in time to spend it is a SCHEDULING problem, and it is not`,
       `solved by moving the threshold.`,
      ].join(NEWLINE));
  }

  const mean = d.runs.reduce((a, b) => a + b, 0) / d.runs.length;
  const lo = Math.min(...d.runs), hi = Math.max(...d.runs);
  const spread = mean === 0 ? 0 : Math.max(hi - mean, mean - lo) / mean;
  record("I4", "PREDICTABILITY", "BASELINE",
    [`same squad, ${RUNS} runs of the full ${d.runs.length ? "" : ""}schedule:`,
     `  ${d.runs.map((r) => "$" + r.toLocaleString()).join("  ")}`,
     `  mean $${Math.round(mean).toLocaleString()}   range $${lo.toLocaleString()}-$${hi.toLocaleString()}`,
     `  max deviation ${(spread * 100).toFixed(1)}%   TARGET <= 25%   ${spread <= 0.25 ? "within" : "VIOLATED"}`,
    ].join(NEWLINE));
}

// ── GROUP B ─────────────────────────────────────────────────────────────────
console.log(NEWLINE + "GROUP B — not measurable yet (blocker named, NOT run)" + NEWLINE);

// I8 / I9 — now that rollover exists, partially measurable.
record("I8", "THE ARC COMPLETES", "PARTIAL",
  ["The arc now RUNS: harness/rollover.mjs walks a career through five season",
   "boundaries and terminates. What cannot be measured is the second half of the",
   "invariant — 'a well-run club reaches the Final, a poorly-run one does not' —",
   "because manager policies (Phase 4) and start modes (Phase 6) do not exist,",
   "so there is no well-run and poorly-run to compare.",
   "",
   "Player vs tier, measured across a real five-season career:",
   "  S1  balance $  500,000  affordable 75.0  Gold 76  gap  -1.0",
   "  S2  balance $1,020,000  affordable 89.5  Gold 78  gap +11.5",
   "  S3  balance $1,540,000  affordable 89.5  Gold 80  gap  +9.5",
   "  S4  balance $2,060,000  affordable 89.5  Gold 82  gap  +7.5",
   "  S5  balance $2,580,000  affordable 89.5  Gold 84  gap  +5.5",
   "",
   "k=2 works: the gap NARROWS from season two onward instead of widening.",
   "The curve has stopped flattening. It has not been solved — nothing here",
   "stops a club farming 30 Bronze events a season, which is Phase 2 gating.",
  ].join(NEWLINE));

record("I9", "MONEY STAYS MEANINGFUL", "VIOLATED",
  ["End-of-arc balance $3,100,000 from a career that played no matches: income",
   "accrues at a flat $520,000 per season regardless of performance.",
   "",
   "Worse than the total is WHEN it stops mattering. By season two a balance of",
   "$1,020,000 already affords the two best players in the game (89.5, the",
   "roster ceiling), and the affordable squad never moves again. Three of the",
   "five seasons have no spending decision left to make.",
   "",
   "Two separate causes: passive income unrelated to results, and a roster whose",
   "ceiling is reachable on one season's earnings. Phase 4 (sponsorship) and",
   "Phase 2 (gating) both bear on it.",
  ].join(NEWLINE));

const BLOCKED = [
  ["I2", "FAILURE IS POSSIBLE",
   "No fail state. isJobAtRisk has zero consumers and there is no sacking path, so 'reaches sacking within three seasons' has nothing to measure. Phase 5."],
  ["I6", "UNDERDOG IS TIGHT, NOT DOOMED",
   "No start modes and no fail state. UNDERDOG/ESTABLISHED are unimplemented, and 'can fail' needs the same sacking path I2 needs. Phase 5 and 6."],
];

for (const [id, name, blocker] of BLOCKED) {
  record(id, name, "BLOCKED", blocker);
}

// ── Summary ─────────────────────────────────────────────────────────────────
console.log(NEWLINE + bar("="));
const a = results.filter((r) => r.verdict === "PASS").length;
const f = results.filter((r) => r.verdict === "FAIL").length;
const b = results.filter((r) => r.verdict === "BLOCKED").length;
const base = results.filter((r) => r.verdict === "BASELINE" || r.verdict === "PARTIAL" || r.verdict === "VIOLATED").length;
console.log(`  ${a} pass, ${f} fail, ${base} baseline, ${b} blocked`);
console.log(bar("="));
process.exit(failures > 0 ? 1 : 0);
