import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import profileRouter from "./profile";
import locationsRouter from "./locations";
import playersRouter from "./players";
import outfitsRouter from "./outfits";
import teamRouter from "./team";
import contractsRouter from "./contracts";
import staffRouter from "./staff";
import trainingRouter from "./training";
import matchesRouter from "./matches";
import seasonsRouter from "./seasons";
import financesRouter from "./finances";
import draftRouter from "./draft";
import leaderboardRouter from "./leaderboard";
import dashboardRouter from "./dashboard";
import olympicsRouter from "./olympics";
import trophiesRouter from "./trophies";
import facilitiesRouter from "./facilities";
import wellbeingRouter from "./wellbeing";
import medicalRouter from "./medical";
import youthScoutingRouter from "./youth-scouting";
import youthLeagueRouter from "./youth-league";
import achievementsRouter from "./achievements";
import continentalScoutingRouter from "./continental-scouting";
import medicalStaffRouter from "./medical-staff";
import attentionRouter from "./attention";
import newsRouter from "./news";
import eventsRouter from "./events";
import careersRouter from "./careers";
import boardConfidenceRouter from "./board-confidence";
import clubTemplatesRouter from "./club-templates";
import poachingRouter from "./poaching";
import aiManagersRouter from "./ai-managers";
import historyRouter from "./history";
import gameApiRouter from "./game-api";
import calendarRouter from "./calendar";
import devRouter from "./dev";
import storageRouter from "./storage";
import unityRouter from "./unity";
import regionalLeagueRouter from "./regional-league";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(locationsRouter);
router.use(playersRouter);
router.use(outfitsRouter);
router.use(teamRouter);
router.use(contractsRouter);
router.use(staffRouter);
router.use(trainingRouter);
router.use(matchesRouter);
router.use(seasonsRouter);
router.use(financesRouter);
router.use(draftRouter);
router.use(leaderboardRouter);
router.use(dashboardRouter);
router.use(olympicsRouter);
router.use(trophiesRouter);
router.use(facilitiesRouter);
router.use(wellbeingRouter);
router.use(medicalRouter);
router.use(youthScoutingRouter);
router.use(youthLeagueRouter);
router.use(achievementsRouter);
router.use(continentalScoutingRouter);
router.use(medicalStaffRouter);
router.use(attentionRouter);
router.use(newsRouter);
router.use(eventsRouter);
router.use(careersRouter);
router.use(boardConfidenceRouter);
router.use(clubTemplatesRouter);
router.use(poachingRouter);
router.use(aiManagersRouter);
router.use(unityRouter);
router.use(historyRouter);
router.use(gameApiRouter);
router.use(devRouter);
router.use(calendarRouter);
router.use(storageRouter);
router.use(regionalLeagueRouter);

export default router;
