#!/usr/bin/env node
/**
 * Write docs/achievements-table.md from ACHIEVEMENT_DEFS.
 *
 * Rob copies each row into Steamworks by hand (API Name, Display Name,
 * Description, two icons), so the table has to BE the code rather than a
 * transcription of it — a description that drifts is a Steam achievement that
 * says something the game does not.
 *
 * The Steam API name is the key, exactly. Run:  node scripts/achievements-table.cjs
 */
const fs = require("fs");
const path = require("path");

const REPO = path.join(__dirname, "..");
const DEFS = path.join(REPO, "artifacts", "api-server", "src", "utils", "achievement-definitions.ts");
const OUT = path.join(REPO, "docs", "achievements-table.md");

const src = fs.readFileSync(DEFS, "utf8");

// Each definition is a { key, name, description, category, check, progress }
// literal. Descriptions may contain a template literal (CONTINENT_COUNT), so
// the value is taken as written and the one substitution is applied after.
const continentCount = (() => {
  const db = fs.readFileSync(path.join(REPO, "lib", "db", "src", "schema", "continents.ts"), "utf8");
  return /CONTINENT_COUNT\s*=\s*(\d+)/.exec(db)?.[1] ?? "6";
})();

const rows = [];
// A definition may carry a line comment between any two of its fields, so the
// gap between them is "whitespace and comments", not "one newline".
const GAP = String.raw`(?:\s*\/\/[^\n]*)*\s*`;
const re = new RegExp(
  String.raw`key:\s*"([a-z_]+)",` + GAP +
  String.raw`name:\s*"([^"]+)",` + GAP +
  String.raw`description:\s*(\x60[^\x60]*\x60|"[^"]*"),` + GAP +
  String.raw`category:\s*"([a-z]+)"`,
  "g",
);
let m;
while ((m = re.exec(src)) !== null) {
  const [, key, name, rawDesc, category] = m;
  const description = rawDesc
    .slice(1, -1)
    .replace(/\$\{CONTINENT_COUNT\}/g, continentCount);
  rows.push({ key, name, description, category });
}

const declared = (src.match(/^\s{4}key:\s*"/gm) ?? []).length;
if (rows.length !== declared) {
  console.error(
    `[achievements-table] FAILED: parsed ${rows.length} of ${declared} definitions.\n` +
    "  A definition is written in a shape this script does not read. Fix the\n" +
    "  script, not the table: a hand-edited table is how Steam and the game\n" +
    "  come to disagree.",
  );
  process.exit(1);
}

const BY_CATEGORY = { career: "Career", competition: "Competition", finance: "Finance", youth: "Youth", legacy: "Legacy" };

let out = `# Achievements — the ${rows.length} keys\n\n`;
out += "Generated by \`node scripts/achievements-table.cjs\` from\n";
out += "\`artifacts/api-server/src/utils/achievement-definitions.ts\`. Do not edit by hand.\n\n";
out += "The **key** is the Steam API Name, exactly as it must be typed into\n";
out += "Steamworks (Settings -> Stats & Achievements -> Achievements -> New Achievement).\n";
out += "Each one also needs two icons, 64x64: coloured for achieved, grey for not.\n\n";

for (const [cat, label] of Object.entries(BY_CATEGORY)) {
  const inCat = rows.filter((r) => r.category === cat);
  if (inCat.length === 0) continue;
  out += `## ${label} (${inCat.length})\n\n`;
  out += "| API Name (key) | Display Name | Description |\n";
  out += "|---|---|---|\n";
  for (const r of inCat) out += `| \`${r.key}\` | ${r.name} | ${r.description} |\n`;
  out += "\n";
}

out += `**Total: ${rows.length}.**\n`;

fs.writeFileSync(OUT, out.replace(/\n/g, "\r\n"));
console.log(`[achievements-table] wrote ${rows.length} achievements to docs/achievements-table.md`);
